name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      file_content:
        required: true
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print file content received from developer repo
        run: |
          echo "===== Message from Developer Repo ====="
          echo "${{ inputs.file_content }}"
