name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      file-path:
        required: true
        type: string

jobs:
  use-dev-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout developer repo
        uses: actions/checkout@v4
        with:
          repository: afnanmalik-eurus/Composite-Action  
          ref: main                               
          
      - name: Print file from developer repo
        run: |
          echo "===== File from Developer Repo ====="
          cat ${{ inputs.file-path }}
